### ISSUE TITLE
Changing question type in editor wipes changes

### ISSUE THREAD

**Issue by ryanmartinneutrino** [etenoch/qlicker#105]
It's a little awkward that one can apparently change the question type (MC, MS, TF, etc) once one has already started typing in the possible answers. Either they should be saved (if someone inadvertently clicks a different choice) or the type of question should be decided before one can start typing answers (probably most logical).

**Comment by etenoch** [comment]
Just to confirm the desired behaviour, the question editor should prevent changing the question type once answer options have been entered.

Another option could be to allow changing question types but before wiping answer options, prompt the user with a popup and warn them that they are about to clear their answers.

**Comment by ryanmartinneutrino** [comment]
I think preventing the question type from being changed once selected might
be the most intuitive solution. Perhaps, one cannot start entering the
options until the type is selected, and then a warning is issued if someone
tries to change the type after they have started entering options.
