### ISSUE TITLE
CKEditor should show the button to toggle between html source and formatted version

### ISSUE THREAD

**Issue by ryanmartinneutrino** [etenoch/qlicker#107]

**Comment by ryanmartinneutrino** [comment]
From playing around with CKEditor, it looks like the html source button can only show if the editor is not "inline" (not the floating version). I think having the source button available might be more important than having it be inline if we have to choose.

**Comment by etenoch** [comment]
When with this CKEditor plugin, allows for source editing with inline editor. http://ckeditor.com/addon/sourcedialog
