### ISSUE TITLE
cfs:gridfs is deprecated

### ISSUE THREAD

**Issue by ryanmartinneutrino** [etenoch/qlicker#128]
It seems risky to depend on it, but not sure what the best alternative would be. One can store files directly in a Mongo Collection (file size limit 8 or 16MB I think? - which is fine for images) or directly into GridFS, but I'm not sure what the best way would be to get the image files back out in the form you need for <img src>. There are alternative packages, but I'm not sure how supported they are... It's a little annoying that all the documentation online refers to FS-Collection... It's also odd that the community hasn't picked up the maintenance of the cfs packages...

**Comment by etenoch** [comment]
Hmm, it looks like the move the gridfs code from here (https://github.com/CollectionFS/DEPRECATING-cfs-gridfs) to inside the CollectionFS repo (https://github.com/CollectionFS/Meteor-CollectionFS/tree/devel/packages/gridfs). So it should be fine.

However, it doesn't really matter. All the file management in Qlicker goes through CollectionFS so we can swap out any of the storage adapters if needed (https://github.com/CollectionFS/Meteor-CollectionFS#storage-adapters). In potential future larger scale deployment, it may be beneficial to move towards a cloud storage adapter (S3 for ex.) to reduce load on the primary mongo database.

**Comment by ryanmartinneutrino** [comment]
ah, I thought that all of CollectionFS was deprecated, but it looks like
some stuff was updated recently on the repository, so hopefully ok then...
