### ISSUE TITLE
Question Preview should not be interactive

### ISSUE THREAD

**Issue by ryanmartinneutrino** [etenoch/qlicker#90]
Shouldn't be able to click on the question preview; probably resolved when a submit button is implemented (although the submit button should not be clickable in preview, maybe greyed out).

**Comment by etenoch** [comment]
ref #70 (behaviour of submit button described in that issue)

In preview mode(/readonly mode), Options will not show/accept selected state, Submit button will not be shown

**Comment by etenoch** [comment]
fixed in #70
