### ISSUE TITLE
Ability to copy questions and sessions

### ISSUE THREAD

**Issue by ryanmartinneutrino** [etenoch/qlicker#92]
For question:
Convenient to be able to copy a question and edit the copy to avoid having to retype a lot of similar stuff

For session:
Copy a whole session (for example multiple sections in a course) -> ideally, we should be able to tag sessions as well (think of when there are many). I would suggest that each session have a user chosen "date field" indicating when the session will run -> then, the list of sessions can be sorted by session date.

**Comment by etenoch** [comment]
- [x] duplicating questions in question library
- [ ] copying questions within a session (@ryanmartinneutrino is this needed?)
- [ ] copying sessions within course & to different courses

Additional session features (tagging, date) in #97

**Comment by ryanmartinneutrino** [comment]
I think it could be useful to easily duplicate a question in a session and then editing it (since often questions can be similar, or variations of each other).  Maybe one way to make this easier is that the default view of questions in the library is to list them as most recent first (maybe this is already in place?). That way, if you duplicate a question in the library, it's easy to find it and add it to the session that one is building, and perhaps nothing would be gained by duplicating it in a session?

**Comment by ryanmartinneutrino** [comment]
For duplicating a question, could it be as a little drop down menu on the summary view of the question (left panel of question library)? You used to have a little "more" dropdown, that seems like and ideal place to put things like:
- copy
- delete
- copy into session
Not critical if you don't do this, just thought I'd mention it...
